#############################################################################
# Makefile for building: libqsqlibase.so
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  ibase.pro
# Template: lib
# Command: /opt/Qt5.5.1/5.5/gcc_64/bin/qmake -o Makefile ibase.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT_NO_TSLIB -DQT_NO_LIBINPUT -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -fvisibility=hidden -fno-exceptions -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -fvisibility=hidden -fvisibility-inlines-hidden -std=c++0x -fno-exceptions -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/5.5.1 -I/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/5.5.1/QtCore -I/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/5.5.1 -I/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/5.5.1/QtSql -I/opt/Qt5.5.1/5.5/gcc_64/include -I/opt/Qt5.5.1/5.5/gcc_64/include/QtSql -I/opt/Qt5.5.1/5.5/gcc_64/include/QtCore -I.moc -I../../../../mkspecs/linux-g++
QMAKE         = /opt/Qt5.5.1/5.5/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qsqlibase1.0.0
DISTDIR = /opt/Qt5.5.1/5.5/Src/qtbase/src/plugins/sqldrivers/ibase/.obj/qsqlibase1.0.0
LINK          = g++
LFLAGS        = -Wl,--no-undefined -Wl,-O1 -Wl,--enable-new-dtags -Wl,-rpath,/opt/Qt5.5.1/5.5/gcc_64 -Wl,-rpath,/opt/Qt5.5.1/5.5/gcc_64 -Wl,-rpath,/opt/Qt5.5.1/5.5/gcc_64/lib -shared
LIBS          = $(SUBLIBS) -lgds -L/opt/Qt5.5.1/5.5/gcc_64/lib -lQt5Sql -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = main.cpp \
		../../../sql/drivers/ibase/qsql_ibase.cpp .moc/moc_qsql_ibase_p.cpp
OBJECTS       = .obj/main.o \
		.obj/qsql_ibase.o \
		.obj/moc_qsql_ibase_p.o
DIST          = ../../../../mkspecs/features/spec_pre.prf \
		../../../../mkspecs/common/unix.conf \
		../../../../mkspecs/common/linux.conf \
		../../../../mkspecs/common/sanitize.conf \
		../../../../mkspecs/common/gcc-base.conf \
		../../../../mkspecs/common/gcc-base-unix.conf \
		../../../../mkspecs/common/g++-base.conf \
		../../../../mkspecs/common/g++-unix.conf \
		../../../../mkspecs/modules-inst/qt_plugin_qsqlibase.pri \
		../../../../mkspecs/modules/qt_plugin_qsqlibase.pri \
		../../../../mkspecs/features/qt_functions.prf \
		../../../../mkspecs/features/qt_config.prf \
		../../../../mkspecs/linux-g++/qmake.conf \
		../../../../mkspecs/features/spec_post.prf \
		../../../../mkspecs/features/qt_build_config.prf \
		../../../../.qmake.conf \
		../../../../mkspecs/features/exclusive_builds.prf \
		../../../../mkspecs/features/default_pre.prf \
		../../../sql/drivers/ibase/qsql_ibase.pri \
		../../../../mkspecs/features/qt_build_paths.prf \
		../../../../mkspecs/features/qt_targets.prf \
		../../../../mkspecs/features/qt_common.prf \
		../../../../mkspecs/features/qt_plugin.prf \
		../qsqldriverbase.pri \
		../../../../mkspecs/features/resolve_config.prf \
		../../../../mkspecs/features/default_post.prf \
		../../../../mkspecs/features/unix/bsymbolic_functions.prf \
		../../../../mkspecs/features/unix/hide_symbols.prf \
		../../../../mkspecs/features/c++11.prf \
		../../../../mkspecs/features/cmake_functions.prf \
		../../../../mkspecs/features/create_cmake.prf \
		../../../../mkspecs/features/qt_example_installs.prf \
		../../../../mkspecs/features/exceptions_off.prf \
		../../../../mkspecs/features/qt_docs_targets.prf \
		../../../../mkspecs/features/precompile_header.prf \
		../../../../mkspecs/features/unix/largefile.prf \
		../../../../mkspecs/features/warn_on.prf \
		../../../../mkspecs/features/qt.prf \
		../../../../mkspecs/features/resources.prf \
		../../../../mkspecs/features/moc.prf \
		../../../../mkspecs/features/unix/thread.prf \
		../../../../mkspecs/features/testcase_targets.prf \
		../../../../mkspecs/features/yacc.prf \
		../../../../mkspecs/features/lex.prf \
		ibase.pro ../../../sql/drivers/ibase/qsql_ibase_p.h main.cpp \
		../../../sql/drivers/ibase/qsql_ibase.cpp
QMAKE_TARGET  = qsqlibase
DESTDIR       = ../../../../plugins/sqldrivers/#avoid trailing-slash linebreak
TARGET        = libqsqlibase.so
TARGETD       = libqsqlibase.so


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

../../../../plugins/sqldrivers/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@test -d ../../../../plugins/sqldrivers/ || mkdir -p ../../../../plugins/sqldrivers/
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-$(MOVE) $(TARGET) ../../../../plugins/sqldrivers/ 



Makefile: ibase.pro ../../../../.qmake.conf ../../../../mkspecs/linux-g++/qmake.conf ../../../../mkspecs/features/spec_pre.prf \
		../../../../mkspecs/common/unix.conf \
		../../../../mkspecs/common/linux.conf \
		../../../../mkspecs/common/sanitize.conf \
		../../../../mkspecs/common/gcc-base.conf \
		../../../../mkspecs/common/gcc-base-unix.conf \
		../../../../mkspecs/common/g++-base.conf \
		../../../../mkspecs/common/g++-unix.conf \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../mkspecs/modules-inst/qt_plugin_qsqlibase.pri \
		../../../../mkspecs/modules/qt_plugin_qsqlibase.pri \
		../../../../mkspecs/features/qt_functions.prf \
		../../../../mkspecs/features/qt_config.prf \
		../../../../mkspecs/linux-g++/qmake.conf \
		../../../../mkspecs/features/spec_post.prf \
		/opt/Qt5.5.1/5.5/gcc_64/mkspecs/qmodule.pri \
		../../../../mkspecs/features/qt_build_config.prf \
		../../../../.qmake.conf \
		../../../../mkspecs/features/exclusive_builds.prf \
		../../../../mkspecs/features/default_pre.prf \
		../../../sql/drivers/ibase/qsql_ibase.pri \
		../../../../mkspecs/features/qt_build_paths.prf \
		../../../../mkspecs/features/qt_targets.prf \
		../../../../mkspecs/features/qt_common.prf \
		../../../../mkspecs/features/qt_plugin.prf \
		../qsqldriverbase.pri \
		../../../../mkspecs/features/resolve_config.prf \
		../../../../mkspecs/features/default_post.prf \
		../../../../mkspecs/features/unix/bsymbolic_functions.prf \
		../../../../mkspecs/features/unix/hide_symbols.prf \
		../../../../mkspecs/features/c++11.prf \
		../../../../mkspecs/features/cmake_functions.prf \
		../../../../mkspecs/features/create_cmake.prf \
		../../../../mkspecs/features/qt_example_installs.prf \
		../../../../mkspecs/features/exceptions_off.prf \
		../../../../mkspecs/features/qt_docs_targets.prf \
		../../../../mkspecs/features/precompile_header.prf \
		../../../../mkspecs/features/unix/largefile.prf \
		../../../../mkspecs/features/warn_on.prf \
		../../../../mkspecs/features/qt.prf \
		../../../../mkspecs/features/resources.prf \
		../../../../mkspecs/features/moc.prf \
		../../../../mkspecs/features/unix/thread.prf \
		../../../../mkspecs/features/testcase_targets.prf \
		../../../../mkspecs/features/yacc.prf \
		../../../../mkspecs/features/lex.prf \
		ibase.pro \
		../../../../mkspecs/features/data/cmake/Qt5PluginTarget.cmake.in \
		/opt/Qt5.5.1/5.5/gcc_64/lib/libQt5Sql.prl \
		/opt/Qt5.5.1/5.5/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile ibase.pro
../../../../mkspecs/features/spec_pre.prf:
../../../../mkspecs/common/unix.conf:
../../../../mkspecs/common/linux.conf:
../../../../mkspecs/common/sanitize.conf:
../../../../mkspecs/common/gcc-base.conf:
../../../../mkspecs/common/gcc-base-unix.conf:
../../../../mkspecs/common/g++-base.conf:
../../../../mkspecs/common/g++-unix.conf:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/qconfig.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../mkspecs/modules-inst/qt_plugin_qsqlibase.pri:
../../../../mkspecs/modules/qt_plugin_qsqlibase.pri:
../../../../mkspecs/features/qt_functions.prf:
../../../../mkspecs/features/qt_config.prf:
../../../../mkspecs/linux-g++/qmake.conf:
../../../../mkspecs/features/spec_post.prf:
/opt/Qt5.5.1/5.5/gcc_64/mkspecs/qmodule.pri:
../../../../mkspecs/features/qt_build_config.prf:
../../../../.qmake.conf:
../../../../mkspecs/features/exclusive_builds.prf:
../../../../mkspecs/features/default_pre.prf:
../../../sql/drivers/ibase/qsql_ibase.pri:
../../../../mkspecs/features/qt_build_paths.prf:
../../../../mkspecs/features/qt_targets.prf:
../../../../mkspecs/features/qt_common.prf:
../../../../mkspecs/features/qt_plugin.prf:
../qsqldriverbase.pri:
../../../../mkspecs/features/resolve_config.prf:
../../../../mkspecs/features/default_post.prf:
../../../../mkspecs/features/unix/bsymbolic_functions.prf:
../../../../mkspecs/features/unix/hide_symbols.prf:
../../../../mkspecs/features/c++11.prf:
../../../../mkspecs/features/cmake_functions.prf:
../../../../mkspecs/features/create_cmake.prf:
../../../../mkspecs/features/qt_example_installs.prf:
../../../../mkspecs/features/exceptions_off.prf:
../../../../mkspecs/features/qt_docs_targets.prf:
../../../../mkspecs/features/precompile_header.prf:
../../../../mkspecs/features/unix/largefile.prf:
../../../../mkspecs/features/warn_on.prf:
../../../../mkspecs/features/qt.prf:
../../../../mkspecs/features/resources.prf:
../../../../mkspecs/features/moc.prf:
../../../../mkspecs/features/unix/thread.prf:
../../../../mkspecs/features/testcase_targets.prf:
../../../../mkspecs/features/yacc.prf:
../../../../mkspecs/features/lex.prf:
ibase.pro:
../../../../mkspecs/features/data/cmake/Qt5PluginTarget.cmake.in:
/opt/Qt5.5.1/5.5/gcc_64/lib/libQt5Sql.prl:
/opt/Qt5.5.1/5.5/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ibase.pro

qmake_all: FORCE


all: Makefile ../../../../plugins/sqldrivers/$(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../sql/drivers/ibase/qsql_ibase_p.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp ../../../sql/drivers/ibase/qsql_ibase.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) ../../../../plugins/sqldrivers/$(TARGET) 
	-$(DEL_FILE) /opt/Qt5.5.1/5.5/Src/qtbase/lib/cmake/Qt5Sql/Qt5Sql_QIBaseDriverPlugin.cmake
	-$(DEL_FILE) Makefile


####### Sub-libraries

html_docs:
	$(MAKE) -f $(MAKEFILE) prepare_docs && $(MAKE) -f $(MAKEFILE) generate_docs

docs:
	$(MAKE) -f $(MAKEFILE) html_docs && $(MAKE) -f $(MAKEFILE) qch_docs

install_html_docs:

uninstall_html_docs:

install_qch_docs:

uninstall_qch_docs:

install_docs:

uninstall_docs:

qch_docs:

prepare_docs:

generate_docs:

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_no_pch_compiler_make_all:
compiler_no_pch_compiler_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: .moc/moc_qsql_ibase_p.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_qsql_ibase_p.cpp
.moc/moc_qsql_ibase_p.cpp: /opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsqlresult.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsql.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsqldriver.h \
		../../../sql/drivers/ibase/qsql_ibase_p.h
	/opt/Qt5.5.1/5.5/gcc_64/bin/moc $(DEFINES) -I/opt/Qt5.5.1/5.5/Src/qtbase/mkspecs/linux-g++ -I/opt/Qt5.5.1/5.5/Src/qtbase/src/plugins/sqldrivers/ibase -I/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/5.5.1 -I/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/5.5.1/QtCore -I/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/5.5.1 -I/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/5.5.1/QtSql -I/opt/Qt5.5.1/5.5/gcc_64/include -I/opt/Qt5.5.1/5.5/gcc_64/include/QtSql -I/opt/Qt5.5.1/5.5/gcc_64/include/QtCore ../../../sql/drivers/ibase/qsql_ibase_p.h -o .moc/moc_qsql_ibase_p.cpp

compiler_moc_source_make_all: .moc/main.moc
compiler_moc_source_clean:
	-$(DEL_FILE) .moc/main.moc
.moc/main.moc: /opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsqldriverplugin.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qplugin.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qpointer.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qjsonobject.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qjsonvalue.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qfactoryinterface.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsql.h \
		../../../sql/drivers/ibase/qsql_ibase_p.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsqlresult.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsqldriver.h \
		main.cpp
	/opt/Qt5.5.1/5.5/gcc_64/bin/moc $(DEFINES) -I/opt/Qt5.5.1/5.5/Src/qtbase/mkspecs/linux-g++ -I/opt/Qt5.5.1/5.5/Src/qtbase/src/plugins/sqldrivers/ibase -I/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/5.5.1 -I/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/5.5.1/QtCore -I/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/5.5.1 -I/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/5.5.1/QtSql -I/opt/Qt5.5.1/5.5/gcc_64/include -I/opt/Qt5.5.1/5.5/gcc_64/include/QtSql -I/opt/Qt5.5.1/5.5/gcc_64/include/QtCore main.cpp -o .moc/main.moc

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_moc_source_clean 

####### Compile

.obj/main.o: main.cpp /opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsqldriverplugin.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qplugin.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qpointer.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qjsonobject.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qjsonvalue.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qfactoryinterface.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsql.h \
		../../../sql/drivers/ibase/qsql_ibase_p.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsqlresult.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsqldriver.h \
		.moc/main.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o main.cpp

.obj/qsql_ibase.o: ../../../sql/drivers/ibase/qsql_ibase.cpp ../../../sql/drivers/ibase/qsql_ibase_p.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsqlresult.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsql.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsqldriver.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qdatetime.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsqlerror.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsqlfield.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsqlindex.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsqlrecord.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsqlquery.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/qsqldatabase.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/5.5.1/QtSql/private/qsqlcachedresult_p.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtSql/5.5.1/QtSql/private/qsqldriver_p.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/5.5.1/QtCore/private/qobject_p.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qpointer.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qreadwritelock.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/qtextcodec.h \
		/opt/Qt5.5.1/5.5/gcc_64/include/QtCore/QVarLengthArray
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/qsql_ibase.o ../../../sql/drivers/ibase/qsql_ibase.cpp

.obj/moc_qsql_ibase_p.o: .moc/moc_qsql_ibase_p.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_qsql_ibase_p.o .moc/moc_qsql_ibase_p.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Qt5.5.1/5.5/gcc_64/plugins/sqldrivers || mkdir -p $(INSTALL_ROOT)/opt/Qt5.5.1/5.5/gcc_64/plugins/sqldrivers
	-$(INSTALL_PROGRAM) ../../../../plugins/sqldrivers/$(TARGET) $(INSTALL_ROOT)/opt/Qt5.5.1/5.5/gcc_64/plugins/sqldrivers/$(TARGET)
	-$(STRIP) --strip-unneeded $(INSTALL_ROOT)/opt/Qt5.5.1/5.5/gcc_64/plugins/sqldrivers/$(TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Qt5.5.1/5.5/gcc_64/plugins/sqldrivers/$(TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Qt5.5.1/5.5/gcc_64/plugins/sqldrivers/ 


install_cmake_qt5_plugin_file: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Qt5.5.1/5.5/gcc_64/lib/cmake/Qt5Sql || mkdir -p $(INSTALL_ROOT)/opt/Qt5.5.1/5.5/gcc_64/lib/cmake/Qt5Sql
	-$(INSTALL_FILE) /opt/Qt5.5.1/5.5/Src/qtbase/lib/cmake/Qt5Sql/Qt5Sql_QIBaseDriverPlugin.cmake $(INSTALL_ROOT)/opt/Qt5.5.1/5.5/gcc_64/lib/cmake/Qt5Sql/

uninstall_cmake_qt5_plugin_file: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Qt5.5.1/5.5/gcc_64/lib/cmake/Qt5Sql/Qt5Sql_QIBaseDriverPlugin.cmake
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Qt5.5.1/5.5/gcc_64/lib/cmake/Qt5Sql/ 


install: install_target install_cmake_qt5_plugin_file  FORCE

uninstall: uninstall_target uninstall_cmake_qt5_plugin_file  FORCE

FORCE:

